### ISSUE TITLE
thanks a lot mate

### ISSUE THREAD

**Issue by SEOHUBS** [serping/serp-checker#3]
appreciate your hard work mate results 100% accurate. tor bhw

**Comment by seadfeng** [comment]
> appreciate your hard work mate results 100% accurate. tor bhw

Thank you for your feedback, the API is currently in the beta stage and it's great to have your positive feedback!

**Comment by SEOHUBS** [comment]
> > appreciate your hard work mate results 100% accurate. tor bhw
> 
> Thank you for your feedback, the API is currently in the beta stage and it's great to have your positive feedback!

am giving my honest review because this is my daily routine now 🖤🔥
